#!/bin/sh

set -e

if [ -n "$KOTLIN_HOME" ]; then
  KOTLIN_LIB="$KOTLIN_HOME/libexec/lib"
else
  echo "environment variable '\$KOTLIN_HOME' is missing" 
fi

KOTLIN_LIB="$KOTLIN_HOME/libexec/lib"
LIBS="$KOTLIN_LIB/kotlin-stdlib.jar:$KOTLIN_LIB/kotlin-compiler.jar:$KOTLIN_LIB/kotlin-daemon-client.jar:/$KOTLIN_LIB/kotlin-daemon.jar"

mkdir -p out/nob

if [ ! -f out/nob/NobKt.class ]; then
    echo "[INFO] bootstrapping nob.kt -> class files"
    kotlinc nob.kt -cp "$LIBS" -d out
fi

java -cp "out:$LIBS" nob.NobKt "$KOTLIN_LIB" $@
