name: main

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build:
    if: github.event.pull_request.merged || github.event_name == 'push' || github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    timeout-minutes: 10
    permissions:
      contents: read
      actions: read
    env: 
      KOTLIN_LIB: /usr/share/kotlinc/lib
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-java@v5.0.0
        with:
          java-version: 21
          distribution: temurin
      - uses: actions/cache@v4
        with:
          path: |
            /home/runner/.nob_cache/
            out/nob/
          key: nob-${{ hashFiles('nob.kt') }}
          restore-keys: nob-
      - name: HACK - Update file timestamps after cache restore
        if: steps.cache.outputs.cache-hit == 'true'
        run: find out/nob/ -type f -exec touch -m {} +
      - run: ./nob test
      - run: ./nob run
      - run: ./nob release example
