name: main

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build:
    if: github.event.pull_request.merged || github.event_name == 'push' || github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    timeout-minutes: 10
    permissions:
      contents: read
      actions: read
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-java@v5.0.0
        with:
          java-version: 21
          distribution: temurin
      - run: ./nob test
        env: 
          KOTLIN_LIB: /usr/share/kotlinc/lib/
